InventoryTracking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path, include


from . import views



app_name = 'app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    path('create-warehouse/', views.CreateWarehouseView.as_view(), name="create-warehouse"),
    path('create-inventory-item/', views.CreateInventoryView.as_view(), name="create-inventory"),
    path('get/ajax/warehouse', views.GetWarehouse, name="get-warehouse"),
    path('detail/<int:pk>/', views.DetailWarehouseView.as_view(), name="detail"),
    path('change-inventory/<int:pk>/', views.ChangeInventory, name="change-inventory"),
    path('delete-inventory/<int:pk>/', views.DeleteInventory, name="delete-inventory"),
    path('delete-warehouse/<int:pk>/', views.DeleteWarehouse, name="delete-warehouse"),
    path('delete-warehouse/verify/<int:pk>/', views.DeleteWarehouseVerify.as_view(), name="delete-warehouse-verify"),
]

app/models.py
from django.db import models 
from mapbox_location_field.models import LocationField

from django.core.validators import MinValueValidator
from django.db import models

# Warehouse
class Warehouse(models.Model):
    location = LocationField(map_attrs={"center": [-77.03, 38.91], "zoom": 9})
    title = models.CharField(max_length=100, blank=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['warehouses'] = Warehouse.objects.all()
        return context

# Inventory item
class InventoryItem(models.Model):
    title = models.CharField(max_length=100, blank=False)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, related_name="inventory_items")
    pub_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now_add=True, null=True)

    amount = models.IntegerField(
        default=1,
        validators=[
            MinValueValidator(1)  # minimum value indicator 
        ]
    )
    measurement = models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return self.title

app/forms.py
from django import forms 
from .models import Warehouse, InventoryItem 

class WarehouseForm(forms.ModelForm):  
    class Meta:  
        model = Warehouse
        fields = '__all__'

class InventoryForm(forms.ModelForm):  
    class Meta:  
        model = InventoryItem
        fields = '__all__'

app/views.py
from asyncio.windows_events import NULL
from operator import ge
from urllib import request
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect

from django.views import generic

from .forms import WarehouseForm, InventoryForm
from .models import InventoryItem, Warehouse

from django.http import JsonResponse

class IndexView(generic.ListView):
    template_name = 'app/index.html'
    context_object_name = 'warehouses'

    def get_queryset(self):
        # Return all warehouses 
        return Warehouse.objects.all()

def GetWarehouse(request):
    if is_ajax(request) and request.method == "GET":
        lat = request.GET.get("lat", None)
        lng = request.GET.get("lng", None)

        try:
            coordinates = (abs(float(lng)), abs(float(lat)))
            sum = coordinates[0] + coordinates[1]

            min_diff = 720 # max possible distance between two coordinates
            warehouse = None

            # Iterate through every warehouse and check which absolute difference to point is smallest
            for wh in Warehouse.objects.all():
                temp_coordinates = wh.location
                temp_sum = abs(temp_coordinates[0]) + abs(temp_coordinates[1])

                if abs(temp_sum - sum) < min_diff and abs(temp_sum - sum) < 0.1:
                    min_diff = abs(temp_sum - sum)
                    warehouse = wh

            if isinstance(warehouse, type(None)): # check if click was not on marker
                return JsonResponse({"valid":False}, status = 200)


            inventory_items = InventoryItem.objects.filter(warehouse = warehouse)

            print(inventory_items)
        except Exception:
            return JsonResponse({"valid":False}, status = 200)
        return JsonResponse((list(inventory_items.values('id', 'title', 'amount', 'measurement', 'warehouse')), warehouse.title, warehouse.id), safe = False) 

# Verifies if request is of ajax
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

class CreateWarehouseView(generic.CreateView):
    template_name = 'app/createWarehouse.html'
    form_class = WarehouseForm
    success_url = reverse_lazy('app:index')

class CreateInventoryView(generic.CreateView):
    template_name = 'app/createInventory.html'
    form_class = InventoryForm
    success_url = reverse_lazy('app:index')    

class DetailWarehouseView(generic.DetailView):
    template_name = 'app/detail.html'
    model = Warehouse

# Function to change inventory on request
def ChangeInventory(request, pk):
    
    if request.method == "POST":
        inventory_item = get_object_or_404(InventoryItem, pk=pk) # creates 404 html respond if inventory item does not exist

        # If input is below 1 or the input field is empty, the inventory will be deleted
        if isinstance(request.POST.get("amount", None), type(None)) or int(request.POST.get("amount", None)) < 1 :
            inventory_item.delete()

        InventoryItem.objects.filter(pk=pk).update(amount=int(request.POST.get("amount")))
        
        return redirect('app:detail', pk=inventory_item.warehouse.id)

def DeleteInventory(request, pk):
    
    inventory_item = get_object_or_404(InventoryItem, pk=pk) # creates 404 html respond if inventory item does not exist
    id = inventory_item.warehouse.id # creates 404 html respond if warehouse item does not exist
    inventory_item.delete() # delete inventory item

    return redirect('app:detail', pk=id)

class DeleteWarehouseVerify(generic.DetailView):
    template_name = 'app/deleteWarehouseVerify.html'
    model = Warehouse

def DeleteWarehouse(request, pk):
    
    warehouse = get_object_or_404(Warehouse, pk=pk)

    for item in warehouse.inventory_items.all():
        item.delete()
    
    warehouse.delete()

    return redirect('app:index')

app/templates/app/createInventory.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html style="padding: 30px;">
  <head>
    <title>Create Inventory Item</title>

    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Simple Inventory Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-warehouse/">Create Warehouse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-inventory-item/">Create Inventory</a>
            </li>
          </ul>
        </div>
    </nav>
    <!-- END NAVIGATION BAR -->  
  </head>
  </head>
  <body>
    <h2>Create Inventory Item</h2>
    <form method="post">
        {% csrf_token %} 
           {{form.as_p}}
           <input type="submit" value="Create"> 
    </form> 
    <footer id="sticky-footer" style="padding: 20px;" class="navbar-light bg-light">
        <div class="container text-center">
          <small>Copyright &copy; Simple Inventory Application, Created by <a href="https://www.linkedin.com/in/dylan-herbig/">Dylan Herbig</a></small>
        </div>
    </footer>
  </body>
</html>

app/templates/app/createWarehouse.html
{% load mapbox_location_field_tags %} 
{% location_field_includes %}
{% include_jquery %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html style="padding: 30px;">
  <head>
    <title>Create Inventory Item</title>

    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Simple Inventory Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-warehouse/">Create Warehouse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-inventory-item/">Create Inventory</a>
            </li>
          </ul>
        </div>
    </nav>
    <!-- END NAVIGATION BAR -->  
  </head>
  </head>
  <body>
    <h2>Create Inventory Item</h2>
    <form method="post">
        {% csrf_token %} 
           {{form.as_p}}
           <input type="submit" value="Create"> 
    </form> 
    {{ form.media }}
    <footer id="sticky-footer" style="padding: 20px;" class="navbar-light bg-light">
      <div class="container text-center">
        <small>Copyright &copy; Simple Inventory Application, Created by <a href="https://www.linkedin.com/in/dylan-herbig/">Dylan Herbig</a></small>
      </div>
     </footer>
  </body>
</html>

app/templates/app/deleteWarehouseVerify.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html style="padding: 30px;">
  <head>
    <title>Detail || {{ warehouse.title }}</title>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />

    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Simple Inventory Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-warehouse/">Create Warehouse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-inventory-item/">Create Inventory</a>
            </li>
          </ul>
        </div>
    </nav>
    <!-- END NAVIGATION BAR -->
  </head>
  <body style="text-align: center;">
      <h4 style="padding-top: 40px"> Are you sure you want to delete {{ warehouse.title }}? All of the following items will be deleted as well:</h4>
      <div class="container" style="position: relative;" width="30%">
        {% for item in warehouse.inventory_items.all %}    
            <div class="row">
                <div class="col-sm">
                    <p>{{ item.amount }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ item.measurement }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ item.title }}</p>
                </div>
            </div>
        {% endfor %}
      </div>
      <div class="container" style="position: relative;" width="30%">
        <div class="row">
            <div class="col-sm">
                <a href="{% url 'app:delete-warehouse' warehouse.id %}">
                    <button style="background-color: red;" class="btn btn-primary">Confirm Delete</button>
                </a>
            </div>
            <div class="col-sm">
                <a href="{% url 'app:index' %}">
                    <button class="btn btn-primary">Cancel</button>
                </a>
            </div>
      </div>
      <footer id="sticky-footer" style="padding: 20px;" class="navbar-light bg-light">
        <div class="container text-center">
          <small>Copyright &copy; Simple Inventory Application, Created by <a href="https://www.linkedin.com/in/dylan-herbig/">Dylan Herbig</a></small>
        </div>
      </footer>
  </body>
</html>

app/templates/app/detail.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html style="padding: 30px;">
  <head>
    <title>Detail || {{ warehouse.title }}</title>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />

    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Simple Inventory Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-warehouse/">Create Warehouse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-inventory-item/">Create Inventory</a>
            </li>
          </ul>
        </div>
    </nav>
    <!-- END NAVIGATION BAR -->
  </head>
  <body>
   <h1 style="text-align: center;">{{ warehouse.title }}</h1>
   <div id='map' width="80%" style='height:300px;'>
        <script>
            mapboxgl.accessToken = 'pk.eyJ1IjoiZGhlcmJpZyIsImEiOiJjbDM4YXgxMHUzdmljM2htdTR3eHJjNDlvIn0.qtQvjiKfid1cZ7i5KRwh9Q';
            var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v10',
            center: [{{ warehouse.location.0 }}, {{ warehouse.location.1 }}],
            zoom: 9
            });
            var marker = new mapboxgl.Marker()
                .setLngLat([{{ warehouse.location.0 }}, {{ warehouse.location.1 }}]) // pass in longitude and latitude of each warehouse
                .setPopup(new mapboxgl.Popup().setHTML("<h4>{{ warehouse.title }}</h4>")) // display title of each warehouse if user clicks on marker
                .addTo(map);
        </script>
   </div>

   <div class="container" style="position: relative;"width="300px">
        {% for item in warehouse.inventory_items.all %}
            
            <form class="" style="padding: 2rem;" action={% url 'app:change-inventory' item.id %} method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm">
                        <input id="amount" name="amount" type="text" value="{{ item.amount }}" min="1"></input>
                    </div>
                    <div class="col-sm">
                        <p>{{ item.measurement }}</p>
                    </div>
                    <div class="col-sm">
                        <p>{{ item.title }}</p>
                    </div>
                    <div class="col-sm">
                        <button type="submit" name="button" class="btn btn-primary">Change</button>
                    </div>
            </form>
                    <div class="col-sm">
                        <a style="color: red;" href="{% url 'app:delete-inventory' item.id %}">
                            {% comment %} <button style="background-color: red;" class="btn btn-primary">Delete</button> {% endcomment %}
                            Delete
                        </a>
                    </div>
                </div>
        {% endfor %}
        <div style="margin: 0;
        -ms-transform: translateY(-50%);
        transform: translateY(-50%); padding: 2rem;">
            <a href={% url 'app:create-inventory' %}>
                <button class="btn btn-primary" style="background-color: green;">Create New Inventory</button>
            </a>
        </div>
   </div>
   <footer id="sticky-footer" style="padding: 20px;" class="navbar-light bg-light">
    <div class="container text-center">
      <small>Copyright &copy; Simple Inventory Application, Created by <a href="https://www.linkedin.com/in/dylan-herbig/">Dylan Herbig</a></small>
    </div>
   </footer>
  </body>
</html>

app/templates/app/index.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html style="padding: 30px;">
  <head>
    <title>Simple Inventory Application</title>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />
  
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Simple Inventory Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-warehouse/">Create Warehouse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-inventory-item/">Create Inventory</a>
            </li>
          </ul>
        </div>
    </nav>
    <!-- END NAVIGATION BAR -->  
  </head>
  <body>
   <h1 style="text-align: center; padding-top: 20px;">Simple Inventory Application</h1>
   <div id='map' width="100%" style='height:500px;'></div>

   <div style="text-align: center; padding-top:50px; padding-bottom:50px;" id="warehouse" class="initial">
    <h2>Please select a warehouse!</h2>
   </div>

   <footer id="sticky-footer" style="padding: 20px;" class="navbar-light bg-light">
    <div class="container text-center">
      <small>Copyright &copy; Simple Inventory Application, Created by <a href="https://www.linkedin.com/in/dylan-herbig/">Dylan Herbig</a></small>
    </div>
   </footer>
  </body>
</html>



<script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiZGhlcmJpZyIsImEiOiJjbDM4YXgxMHUzdmljM2htdTR3eHJjNDlvIn0.qtQvjiKfid1cZ7i5KRwh9Q';
    var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v10',
    center: [-77.03, 38.91],
    zoom: 9
    });
    {% for warehouse in warehouses %}
        var marker = new mapboxgl.Marker()
        .setLngLat([{{ warehouse.location.0 }}, {{ warehouse.location.1 }}]) // pass in longitude and latitude of each warehouse
        .setPopup(new mapboxgl.Popup().setHTML("<h4>{{ warehouse.title }}</h4>")) // display title of each warehouse if user clicks on marker
        .addTo(map);
    {% endfor %}

    map.on('load', () => {
        map.addSource('locations', {
            'type': 'geojson',
            'data': {
                'type': 'FeatureCollection',
                'features': [
                    {
                    {% for warehouse in warehouses %}
                        'type': 'Feature',
                        'properties': {
                            'title': '{{ warehouse.title }}'
                        },
                        'geometry': {
                            'type': 'Point',
                            'coordinates': [{{ warehouse.location.0 }}, {{ warehouse.location.1 }}]
                        },
                    {% endfor %}
                    }
                    
                ]
            }
        })
    });


    map.on('click', (e) => {

        let coords = e.lngLat; /* coordinates of click */

        $.ajax({
            type: "GET",
            url: "{% url 'app:get-warehouse' %}",   /* Call python function in this script */
            data: {"lat": coords.lat, "lng": coords.lng},   /* Passing the coordinates data */
            success: function (response) {

                var inventory = response[0];

                if ($("#warehouse").hasClass("initial")) {
                    $("#warehouse").empty();
                }

                if ($("#warehouse").hasClass("element")) {
                    $("#warehouse").empty();
                } else {
                    $("#warehouse").addClass("element");
                }

                console.log(response);

                $("#warehouse").append(
                    `<h2>${response[1]||""}</h2>`
                )

                for (let i = 0; i < inventory.length; i++) {
                    $("#warehouse").append(
                        `<p>${inventory[i]["amount"]||""}x ${inventory[i]["title"]||""} ${inventory[i]["measurement"]||""}</p>`
                    )
                }

                $("#warehouse").append(
                    `<a href="http://127.0.0.1:8000/detail/${response[2]}"><button>View Details</button></a> \n` +
                    `<a href="http://127.0.0.1:8000/delete-warehouse/verify/${response[2]}"><button>Delete Warehouse</button></a>`
                )
            }
        });

    });
</script>